Added specs for Gem
Wolox/wor-requests pull request #22
Opened 2017-05-02 13:13 UTC by mishuagopian

## Summary
- Added specs for gem

2017-05-02 13:39 UTC, alebian requested changes

2017-05-02 13:39 UTC, alebian commented on .rubocop.yml
> +    - spec/**/*
:unamused: :smirk:

2017-05-02 13:39 UTC, alebian commented on spec/spy.rb
> +class Spy
emoushon

2017-05-02 13:39 UTC, alebian commented on spec/wor/requests/base_spec.rb
> +# require 'spec_helper'
Why is this file all commented out? Delete it if it is not necessary

2017-05-02 13:39 UTC, alebian commented on spec/wor/test_services/some_service.rb
> +  VALID_HTTP_VERBS = %i(get post patch put delete).freeze
You can use the array defined in Wor::Requests::Base::VALID_HTTP_VERBS. I think this line is not necessary

2017-05-02 18:50 UTC, draffo-dc requested changes

2017-05-02 18:50 UTC, Enanodr commented on spec/wor/test_services/some_service_failure_spec.rb
> +          it 'logger.info has been called once' do
if logger.info has been called once why are you checking if eq(0) ?

2017-05-02 18:50 UTC, Enanodr commented on spec/wor/test_services/some_service_failure_spec.rb
> +            expect(service.logger.spied_error_counter).to be(0)
idem

2017-05-02 18:50 UTC, Enanodr commented on spec/wor/test_services/some_service_successful_spec.rb
> +            expect(service.logger.spied_info_counter).to be(0)
idem

2017-05-03 11:57 UTC, mishuagopian commented on .rubocop.yml
> +    - spec/**/*
👼

2017-05-03 12:43 UTC, mishuagopian commented
@Enanodr @alebian back to you guys

2017-05-03 12:47 UTC, alebian approved these changes
Looks good to me! :+1:

2017-05-03 15:19 UTC, draffo-dc approved these changes

2017-05-03 16:00 UTC, merged