Add doc for post with token
Wolox/wor-requests pull request #34
Opened 2017-10-03 21:24 UTC by gussiciliano

## SUMMARY
- add doc for post with token

## ISSUE
https://github.com/Wolox/wor-requests/issues/33

2017-10-03 21:25 UTC, gussiciliano commented
@mishuagopian i don't know to who assign this PR, anyway, I can't options to using jaja

2017-10-03 21:54 UTC, hdf1996 approved these changes
:D

2017-10-03 22:18 UTC, gussiciliano commented
:gus-zoom-very-happy:

2017-10-03 22:45 UTC, alebian requested changes

2017-10-03 22:45 UTC, alebian commented on README.md
> +        Authorization: authorization
What do you think of adding a 'Content-type' header to the get example above?

2017-10-03 22:45 UTC, alebian commented on README.md
> +If you work with Authorization token you can write something like this:
If you need to send body parameters in a post request..

2017-10-03 22:45 UTC, alebian commented on README.md
> +      attempting_to: 'post to an external service',
`'Make a POST request to an external service.'`

2017-10-03 22:45 UTC, alebian commented on README.md
> +  def request_to_post(authorization)
I'd call this `post_request_example`

2017-10-04 14:44 UTC, gussiciliano commented
@alebian the changes are already :D

2017-10-11 21:30 UTC, gussiciliano commented
@alebian remember check this PR :D

2017-10-18 19:47 UTC, alebian approved these changes

2017-10-18 19:48 UTC, merged