Handling the case when response body is empty.
Wolox/wor-requests pull request #39
Opened 2019-07-02 17:59 UTC by mnmallea

# Summary
- Fixed the issue described in #37.
- Added test cases to consider responses with empty bodies.

2019-09-03 11:44 UTC, nicozar95 commented on spec/wor/test_services/some_service_head_succesful_spec.rb
> +          subject(:service) { described_class.new }
You are repeating the subject here and in the above context, move this subject into the parent context `context 'when calling with attempting_to field defined'` of both:
- `context 'when calling without block' do `
- `context 'when calling with block'`

2019-09-03 11:44 UTC, nicozar95 commented on wor-requests.gemspec
> +  spec.add_development_dependency 'bundler'
Why remove the bundler version?

2019-09-03 14:27 UTC, blacksam07 commented
Change your destination branch  to `development`

2019-09-30 16:12 UTC, wleoguty91 requested changes

2019-09-30 16:12 UTC, wleoguty91 commented on spec/wor/test_services/some_service.rb
> +      JSON.parse(response.body)['array'].reduce('', :+) if response.body.present?
This line is equal to the line in method `method_with_log_with_block`... You can refactor this, move to another method and avoid make repetition in your code

2019-09-30 18:04 UTC, holywyvern approved these changes

2019-10-01 18:00 UTC, wleoguty91 requested changes

2019-10-01 18:00 UTC, wleoguty91 commented on spec/wor/test_services/some_service_head_succesful_spec.rb
> +        context 'when calling with block' do
This context is the same as the context above ... This is not right :confused:

2019-10-01 18:00 UTC, wleoguty91 commented on spec/wor/test_services/some_service_head_succesful_spec.rb
> +        context 'when calling with block' do
Same here

2019-10-03 15:38 UTC, wleoguty91 approved these changes

2019-10-03 15:39 UTC, jhonmunoz approved these changes
lgtm 🍪

2019-10-03 16:23 UTC, merged