Refactored ExternalApiService class
Wolox/wor-requests pull request #8
Opened 2017-03-03 23:29 UTC by alebian

2017-03-04 06:49 UTC, draffo-dc requested changes

2017-03-04 06:49 UTC, Enanodr commented on lib/wor/requests/request_error.rb
> +    class RequestError < StandardError; end
We need the response in the exception, otherwise the service cannot retrieve any information from the the failed request

2017-03-06 11:58 UTC, hdf1986 commented on lib/wor/requests/base.rb
> +      VALID_GET_ATTRIBUTES    = VALID_COMMON_ATTRIBUTES + [:query]
Maybe we should need to freeze these arrays? I think that the concatenation of a frozen array with a non-frozen array returns a non-frozen array U_U

2017-03-06 12:03 UTC, hdf1986 commented on lib/wor/requests/base.rb
> +      # rubocop:disable MethodLength
We can do something about this? I mean, at least we can divide the if-else in two more methods, one for failure and other for success.

2017-03-06 12:07 UTC, hdf1986 commented on lib/wor/requests/base.rb
> +        !!object
http://stackoverflow.com/a/40159970/4870465 I think this can be useful :D

2017-03-06 12:08 UTC, hdf1986 commented
Great job!

2017-03-06 19:19 UTC, icoluccio commented on lib/wor/requests/base.rb
> +      def get(opts = {}, &block)
I'd personally use metaprogramming for this. if possible

2017-03-06 19:19 UTC, icoluccio commented on lib/wor/requests/base.rb
> +        !!object
Agreed on that

2017-03-06 19:58 UTC, hdf1986 commented on lib/wor/requests/base.rb
> +      def get(opts = {}, &block)
Sounds good, we can use VALID_HTTP_VERBS to iterate and define the methods

2017-03-06 20:01 UTC, gastonponti commented on lib/wor/requests/base.rb
> +      def get(opts = {}, &block)
Something like this should work:
```
VALID_HTTP_VERBS.each do |method|
  define_method(method) do |opts = {}, &block|
    request(
      opts.select { |k, _v| self.class.class_eval("VALID_#{method.upcase}_ATRIBUTES").include?(k) }.merge(method: method),
      &block
    )
  end  
end
```

2017-03-07 12:52 UTC, alebian commented on lib/wor/requests/base.rb
> +        !!object
Rails uses this for present... https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activesupport/lib/active_support/core_ext/object/blank.rb

2017-03-07 13:32 UTC, alebian commented
@Enanodr @icoluccio @gastonponti @hdf1986 Applied changes that you suggested.

I created HTTP_COMPLETE and HTTP_QUERY_ONLY because redefining the array for every request method looked bad.
I also created the constantize method because self.class.class_eval made the line too long, and using do;end made the code look ugly.

2017-03-07 15:28 UTC, ilanusse reviewed
LGTM!

2017-03-07 19:39 UTC, draffo-dc approved these changes

2017-03-07 19:40 UTC, merged